##
## run DESeq2 on the htseq-counts files.
##

library(DESeq2)

directory = "htseq/"

## reads.txt describes the experiment
reads = read.table("reads.txt", sep="\t", row.names=1, col.names=c("id","tissue","samplename"))

##          tissue                  samplename
## ACMLCM1  whole embryo sac1       WES1
## ACMLCM2  whole embryo sac2	    WES2
## ACMLCM3  whole embryo sac3	    WES3
## ACMLCM4  whole embryo sac4	    WES4
## ACMLCM5  antipodal cell cluster1 ACC1
## ACMLCM6  antipodal cell cluster2 ACC2
## ACMLCM7  antipodal cell cluster3 ACC3
## ACMLCM8  antipodal cell cluster4 ACC4
## ACMLCM9  central cell1	    CC1
## ACMLCM10 central cell2	    CC2
## ACMLCM11 central cell3	    CC3
## ACMLCM12 central cell4	    CC4
## ACMLCM13 egg apparatus1	    EA1
## ACMLCM14 egg apparatus2	    EA2
## ACMLCM15 egg apparatus3	    EA3
## ACMLCM16 egg apparatus4	    EA4
## ACMLCM17 nucellus1	            N1
## ACMLCM18 nucellus2	            N2
## ACMLCM19 nucellus3	            N3
## ACMLCM20 nucellus4	            N4
## ACMLCM21 pericarp1	            P1
## ACMLCM22 pericarp2	            P2
## ACMLCM23 pericarp3	            P3
## ACMLCM24 pericarp4	            P4

## sampleTable: for htseq-count: a ‘data.frame’ with three or more
##           columns. Each row describes one sample. The first column is
##           the sample name, the second column the file name of the count
##           file generated by htseq-count, and the remaining columns are
##           sample metadata which will be stored in ‘colData’

sampleTable = data.frame(row.names=rownames(reads))
sampleTable$samplename = reads$samplename
sampleTable$filename = paste("gsnap-B73-",rownames(reads),".htseq-count.txt",sep="")
sampleTable$tissue = c("WES","WES","WES","WES",
                       "ACC","ACC","ACC","ACC",
                       "CC","CC","CC","CC",
                       "EA","EA","EA","EA",
                       "N","N","N","N",
                       "P","P","P","P")

dds = DESeqDataSetFromHTSeqCount(sampleTable = sampleTable,
                                 directory = directory,
                                 design = ~ tissue)

## filter out low-count genes
dds = dds[rowSums(counts(dds))>=10,]

## filter out genes starting with "ENSRNA"
dds = dds[substr(rownames(dds),1,6)!="ENSRNA",]


## run DESeq and get results
dds.WES.ACC = DESeq(dds, fitType="local")
res.WES.ACC = results(dds.WES.ACC)
res.WES.ACC = res.WES.ACC[!is.na(res$pvalue),]
res.WES.ACC = res.WES.ACC[!is.na(res$padj),]
