## run DESeq2 on the pruned htseq-counts files.
##
## NOTE: you must have already loaded the merged VCF records and defined the experiment with read-merged.R

library(DESeq2)

## sampleTable: for htseq-count: a ‘data.frame’ with three or more
##           columns. Each row describes one sample. The first column is
##           the sample name, the second column the file name of the count
##           file generated by htseq-count, and the remaining columns are
##           sample metadata which will be stored in ‘colData’

## sampleTable <- data.frame(sampleName = sampleFiles,
##                           fileName = sampleFiles,
##                           condition = sampleCondition)

if (mixSampleName=="S35464" && refSampleName=="SS354+355" && altSampleName=="PS422") {
    if (matches=="perfect") {
        ## REF
        sampleTable = data.frame(row.names=c(
                                     "SS354+355_0",
                                     "SS354+355_2",
                                     "SS354+355_3",
                                     "S35464_1",
                                     "S35464_2",
                                     "S35464_4"
                                 ))
    } else {
        ## ALT
        sampleTable = data.frame(row.names=c(
                                     "PS422_1",
                                     "PS422_2",
                                     "PS422_3",
                                     "S35464_1",
                                     "S35464_2",
                                     "S35464_4"
                                 ))
    }
}

if (mixSampleName=="S364_354" && refSampleName=="SS364" && altSampleName=="YX24") {
    if (matches=="perfect") {
        ## REF
        sampleTable = data.frame(row.names=c(
                                     "SS364_1",
                                     "SS364_2",
                                     "SS364_3",
                                     "S364_354_0",
                                     "S364_354_1",
                                     "S364_354_3"
                                 ))
    } else {
        ## ALT
        sampleTable = data.frame(row.names=c(
                                     "YX24_2",
                                     "YX24_5",
                                     "YX24_10",
                                     "S364_354_0",
                                     "S364_354_1",
                                     "S364_354_3"
                                 ))
    }
}

if (mixSampleName=="S364_354" && refSampleName=="YX24" && altSampleName=="SS364") {
    if (matches=="perfect") {
        ## REF
        sampleTable = data.frame(row.names=c(
                                     "YX24_2",
                                     "YX24_5",
                                     "YX24_10",
                                     "S364_354_0",
                                     "S364_354_1",
                                     "S364_354_3"
                                 ))
    } else {
        ## ALT
        sampleTable = data.frame(row.names=c(
                                     "SS364_1",
                                     "SS364_2",
                                     "SS364_3",
                                     "S364_354_0",
                                     "S364_354_1",
                                     "S364_354_3"
                                 ))
    }
}

if (mixSampleName=="S35464" && refSampleName=="PS422" && altSampleName=="SS354+355") {
    if (matches=="perfect") {
        ## REF
        sampleTable = data.frame(row.names=c(
                                     "PS422_1",
                                     "PS422_2",
                                     "PS422_3",
                                     "S35464_1",
                                     "S35464_2",
                                     "S35464_4"
                                 ))
    } else {
        ## ALT
        sampleTable = data.frame(row.names=c(
                                     "SS354+355_0",
                                     "SS354+355_2",
                                     "SS354+355_3",
                                     "S35464_1",
                                     "S35464_2",
                                     "S35464_4"
                                 ))
    }
}

## build the sample table
sampleTable$sampleName = rownames(sampleTable)
sampleTable$fileName = paste("STAR-",reference,"-",rownames(sampleTable),"/htseq-count.",matches,".pruned.txt",sep="")
sampleTable$condition = factor(c(rep(refSampleName,3), rep(mixSampleName,3)), levels=c(refSampleName,mixSampleName))

## fill the DESeqDataSet and set the reference level
dds = DESeqDataSetFromHTSeqCount(sampleTable = sampleTable, design = ~ condition)

## filter out low-count genes
dds = dds[rowSums(counts(dds))>=10,]

## filter out genes starting with "ENSRNA"
dds = dds[substr(rownames(dds),1,6)!="ENSRNA",]

## run DESeq and get results
dds = DESeq(dds)
res = results(dds)

## get rid of the NA values
res = res[!is.na(res$pvalue),]
res = res[!is.na(res$padj),]
