##
## run DESeq2 on the htseq-counts files.
##

library(DESeq2)

directory = "htseq.B73/"

## reads.txt describes the experiment
reads = read.table("reads.B73.txt", sep="\t", row.names=1, col.names=c("id","sampletype","samplename"))

## id                   sampletype                                             samplename
## STAR-B73-YX24	B73 pollen mapped to B73	                     P.B73.B73
## STAR-B73-PS422	W22 pollen mapped to B73	                     P.W22.B73
## STAR-B73-S35464	B73 silks pollinated with W22 pollen mapped to B73   S.B73.P.W22.B73
## STAR-B73-S364_354	W22 silks pollinated with B73 pollen mapped to B73   S.W22.P.B73.B73
## STAR-B73-SS354+355	B73 silks (unpollinated) mapped to B73	             S.B73.B73
## STAR-B73-SS364	W22 silks (unpollinated) mapped to B73	             S.W22.B73

## sampleTable: for htseq-count: a ‘data.frame’ with three or more
##           columns. Each row describes one sample. The first column is
##           the sample name, the second column the file name of the count
##           file generated by htseq-count, and the remaining columns are
##           sample metadata which will be stored in ‘colData’

sampleTable = data.frame(row.names=rownames(reads))
sampleTable$samplename = reads$samplename
sampleTable$filename = paste(rownames(reads),".htseq-count.txt",sep="")
## only one file per sampletype
sampleTable$sampletype = reads$sampletype

dds = DESeqDataSetFromHTSeqCount(sampleTable = sampleTable,
                                 directory = directory,
                                 design = ~ sampletype)

## filter out low-count genes
dds = dds[rowSums(counts(dds))>=10,]

## filter out genes starting with "ENSRNA"
dds = dds[substr(rownames(dds),1,6)!="ENSRNA",]
